### ISSUE TITLE
Not compatible with LabVIEW 2015/2016

### ISSUE THREAD

**Issue by amahpour** [joerg/LabViewGitEnv#7]
Need to add [case statements in LVDetect.sh](https://github.com/joerg/LabViewGitEnv/blob/windows/etc/LVDetect.sh#L3-L29) to handle LabVIEW 2015 and 2016. Better yet, probably shouldn't be hard-coding this in. 

As a work around I just changed the LabVIEW [executable](https://github.com/joerg/LabViewGitEnv/blob/windows/etc/LVConfig.sh#L4) and [shared](https://github.com/joerg/LabViewGitEnv/blob/windows/etc/LVConfig.sh#L7) paths in LVConfig.sh.

**Comment by joerg** [comment]
Hi,
I am not actively working with LabView any more so I would gladly accept any pull requests. :wink:
You are right, hard coding never is a good idea, but this was the easiest way to go because I explicitly did not want to use anything else but Bash so this project could, at least in theory, be used on Mac and Linux too. However, chaning the paths in the LVConfig.sh for sure is the way to go...
